#!/usr/bin/env bash

RESOLVED_DIR=$(dirname "$(realpath "${0}")")

CAPITALS=$(cat "${RESOLVED_DIR}/../lib/country-list.json")
readonly CAPITALS
COUNTRIES=$(echo "${CAPITALS}" | jq 'keys[]')
readonly COUNTRIES
COUNTRIES_TOTAL=$(echo "${COUNTRIES}" | wc -l)
readonly COUNTRIES_TOTAL

function random_country() {
	local -r index=$((RANDOM % COUNTRIES_TOTAL + 1))

	echo "${COUNTRIES}" |
		head -n ${index} |
		tail -n 1
}
