#!/usr/bin/env bash

# This file contains some features used in almost every script

# Default `figlet` font
readonly TIMER_FIGLET_FONT="contessa"

# ${1} String to repeat
# ${2} Repeat iteration amount
function repeat_string() {
	local tmp=""

	for ((i = 0; i < ${2}; i++)); do
		tmp+=${1}
	done

	# shellcheck disable=SC2086
	printf "%s" ${tmp}
}

# ${1} Time (in seconds)
function simple_timer() {
	date -d@$((${1})) -u +%H:%M:%S
}

# ${1} Time (in seconds)
# ${2} Figlet font name (optional)
function fancy_timer() {
	local -r font_name=${2:-${TIMER_FIGLET_FONT}}

	figlet -f "${font_name}" "$(simple_timer "${1}")"
}

# ${1} Total time (in milliseconds)
# ${2} Notification ID
# ${3} Urgency level
# ${4} Summary
# ${5} Timer function prefix name ("simple" or "fancy"), by default "simple"
function timer() {
	local total=$((${1} / 1000))

	local func

	case ${5} in
	"fancy" | "simple")
		func="${5}_timer"
		;;

	*)
		func="simple_timer"
		;;
	esac

	for ((i = total; i >= 0; i--)); do
		notify-send \
			-r "${2}" \
			-u "${3}" \
			"${4}" "$(${func} ${i})"
		sleep 1
	done
}
