name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - uses: mfinelli/setup-shfmt@v3
      - run: shfmt -d bin/* lib/sc-*
